<%%= initial_stage %>

# ENV RUBY_YJIT_ENABLE=1


<%%= runtime_packages_stage %>


<%%= buildtime_packages_stage %>


<%%= gems_stage %>


<%% if node? -%>
<%%= node_modules_stage %>


<%% end -%>
<%%= final_stage user: "rails", workdir: "/rails" %>

<%%= prepare_app %>

<%%= expose_server %>
